db:
  images: klaemo/couchdb:2.0.0
  ports:
    - "5984:5984"
  environment:
    - COUCHDB_USER=emanuel
    - COUCHDB_PASSWORD=1234

app:
  image: ibmcom/swift-ubuntu
  ports:
    - "8080:8080"
  volumes:
    - .:/root/FoodTruckAPI
  command: bash -c "cd /root/FoodTruckAPI && swift build --clean && swift build --configuration release && ./.build/release/FoodTruckServer"
  links:
    - db:localhost
